### ISSUE TITLE
datahub:index:rebuild configName indexes unrelated objects

### ISSUE THREAD

**Issue by NiklasBr** [BrandOriented/SimpleRESTAdapterBundle#57]
### Pimcore version(s) affected

11.2.3

### Description

When running the command `bin/console datahub:index:rebuild mycomfigname` I expect it to re-index DataObjets only in the given config.

Instead it also indexes unrelated DataObjects.

### How to reproduce

Example config name:

```yaml
pimcore_data_hub:
    configurations:
        ci_hub_1:
            general:
                active: 'on'
                type: ciHub
                name: ci_hub_1
                description: ''
                modificationDate: 1716993974
                path: null
                createDate: 1715938788
            schema:
                assets:
                    enabled: 'on'
                    allowOriginalImage: 'on'
                    thumbnails:
                        - card
                        - detail_print
                dataObjectClasses:
                    -
                        id: Product
                        name: Product
                        columnConfig:
                            id:
                                name: id
                                position: 1
                                hidden: false
                                fieldConfig:
                                    key: id
                                    label: ID
                                    type: system
                            articleNumber:
                                name: articleNumber
                                position: 2
                                hidden: false
                                fieldConfig:
                                    key: articleNumber
                                    label: 'Article number (articleNumber)'
                                    type: input
                            GTIN:
                                name: GTIN
                                position: 3
                                hidden: false
                                fieldConfig:
                                    key: GTIN
                                    label: 'GTIN (13 tall) (GTIN)'
                                    type: input
                            productNumber:
                                name: productNumber
                                position: 4
                                hidden: false
                                fieldConfig:
                                    key: productNumber
                                    label: 'Product number (productNumber)'
                                    type: input
                            productDescription:
                                name: productDescription
                                position: 5
                                hidden: false
                                fieldConfig:
                                    key: productDescription
                                    label: 'Product name (productDescription)'
                                    type: input
                            description:
                                name: description
                                position: 6
                                hidden: false
                                fieldConfig:
                                    key: description
                                    label: 'Product description'
                                    type: wysiwyg
                            urlSlug:
                                name: urlSlug
                                position: 7
                                hidden: false
                                fieldConfig:
                                    key: urlSlug
                                    label: 'URL Slug (urlSlug)'
                                    type: urlSlug
                            available:
                                name: available
                                position: 8
                                hidden: false
                                fieldConfig:
                                    key: available
                                    label: 'Available in market'
                                    type: checkbox
                        language: en
            labelSettings:
                -
                    id: system.id
                -
                    id: system.key
                -
                    id: system.fullPath
                -
                    id: system.parentId
                -
                    id: system.type
                -
                    id: system.subtype
                -
                    id: system.hasChildren
                -
                    id: system.creationDate
                -
                    id: system.modificationDate
                -
                    id: system.locked
                -
                    id: system.versionCount
                -
                    id: system.currentVersion
                -
                    id: system.checksum
                -
                    id: system.mimeType
                -
                    id: system.fileSize
                -
                    id: binaryData.original
                -
                    id: binaryData.card
                -
                    id: binaryData.detail_print
                -
                    id: binaryData.galleryThumbnail
                -
                    id: dimensionData.width
                -
                    id: dimensionData.height
            workspaces: {  }
            permissions:
                user: {  }
                role: {  }
```

Then run `bin/console datahub:index:rebuild ci_hub_1`
